import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

# 1. Load the dataset generated by NNLogging
csv_path = "ftc_shot_data.csv"
if not os.path.exists(csv_path):
    raise FileNotFoundError(
        f"Could not find '{csv_path}'. Make sure to pull it from the Control Hub first!"
    )

df = pd.read_csv(csv_path)

# --- DATA AUGMENTATION BLOCK ---
print(f"Original dataset size: {len(df)} samples.")
augmented_rows = []

for _, row in df.iterrows():
    # A. Keep the original real-world data point
    augmented_rows.append(row.to_dict())

    # B. Field Mirror Symmetry
    # Inverting angle_error, vel_y, and omega creates a mathematically
    # identical shot mirrored across the field's centerline.
    mirror_row = row.copy()
    mirror_row['angle_error'] = -row['angle_error']
    mirror_row['vel_y'] = -row['vel_y']
    mirror_row['omega'] = -row['omega']
    augmented_rows.append(mirror_row.to_dict())

    # C. Sensor Noise Jitter Injection
    # Generates 3 variations of both the original and mirrored shot with slight random deviations
    # to simulate real-world odometry drift, voltage bounce, and localization errors.
    for _ in range(3):
        for base_row in [row, mirror_row]:
            jitter_row = base_row.copy()
            jitter_row['target_dist'] += np.random.normal(0, 0.05)  # +/- 5 cm distance jitter
            jitter_row['angle_error'] += np.random.normal(0, 0.01) # +/- ~0.5 degree angular drift
            jitter_row['voltage'] += np.random.normal(0, 0.1)      # +/- 0.1V transient battery sag
            augmented_rows.append(jitter_row.to_dict())

# Overwrite df with the expanded dataset
df = pd.DataFrame(augmented_rows)
print(f"Augmented dataset size: {len(df)} samples (8x expansion!).\n")
# -------------------------------

# Define feature columns and target label
features = ["target_dist", "angle_error", "vel_x", "vel_y", "omega", "voltage"]
target = "balls_scored"

X = df[features].values
y = df[target].values

# Normalize the target to a 0.0 - 1.0 success metric (assuming max 3 balls per shot)
y = y / 3.0

# 2. Perform the 80% Train and 20% Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

# 3. Scale features (Critical for NN convergence)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Print scaling values so you can apply identical normalization transforms if needed
print("Mean values for scaling:", scaler.mean_)
print("Variance values for scaling:", scaler.var_)

# 4. Define the Neural Network Architecture
model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation='relu', input_shape=(len(features),)),
    tf.keras.layers.Dropout(0.2),  # Randomly drops 20% of nodes to prevent memorization
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dropout(0.1),  # Randomly drops 10% of nodes
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer="adam", loss="mean_squared_error", metrics=["mae"])

# 5. Train the Model
print("\n--- Starting Training Stage ---")
history = model.fit(
    X_train_scaled,
    y_train,
    validation_data=(X_test_scaled, y_test),
    epochs=200,
    batch_size=8,
    verbose=1,
)

# 6. Export directly to .tflite format for your Robot Code
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open("shot_predictor.tflite", "wb") as f:
    f.write(tflite_model)
print("\n Done! Model successfully saved as 'shot_predictor.tflite'")

# 7. Generate Performance Charts
plt.figure(figsize=(12, 5))

# Plot 1: Loss curves across epochs
plt.subplot(1, 2, 1)
plt.plot(history.history["loss"], label="Training Loss (80%)", color="blue")
plt.plot(
    history.history["val_loss"],
    label="Validation Loss (20%)",
    color="orange",
    linestyle="--",
)
plt.title("Model Loss Optimization (MSE)")
plt.xlabel("Epochs")
plt.ylabel("Loss Matrix Error")
plt.legend()
plt.grid(True)

# Plot 2: Actual vs Predicted Scatter Verification
y_pred = model.predict(X_test_scaled)

plt.subplot(1, 2, 2)
plt.scatter(y_test, y_pred, alpha=0.6, color="purple")
plt.plot([0, 1], [0, 1], color="red", linestyle=":")  # Ideal diagonal line
plt.title("Prediction Accuracy Check")
plt.xlabel("Actual Score (Normalized)")
plt.ylabel("Predicted Score (Model Output)")
plt.grid(True)

plt.tight_layout()
plt.savefig("model_training_performance.png")
plt.show()